# Generated by Django 2.0.6 on 2018-06-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_data_collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Vendor_p1',
        ),
    ]
