# Generated by Django 2.0.6 on 2018-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('availability', models.CharField(choices=[('year', 'Yearly'), ('season', 'Seasonally')], default='year', max_length=20)),
                ('paytm_available', models.BooleanField(default=False)),
                ('vendor_type', models.CharField(choices=[('ice-cream', 'Ice Cream Vendor'), ('vegetables', 'Vegetable/Fruits Vendor'), ('street-food', 'Street Food Vendor'), ('drinks', 'Drinks')], default='street-food', max_length=20)),
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
