# Generated by Django 2.0.6 on 2018-06-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_data_collection', '0002_auto_20180623_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=7)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Submitters',
            fields=[
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('submitter', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('availability', models.CharField(choices=[('year', 'Yearly'), ('season', 'Seasonally')], default='year', max_length=20)),
                ('paytm_available', models.BooleanField(default=False)),
                ('vendor_type', models.CharField(choices=[('ice-cream', 'Ice Cream Vendor'), ('vegetables', 'Vegetable/Fruits Vendor'), ('street-food', 'Street Food Vendor'), ('drinks', 'Drinks')], default='street-food', max_length=20)),
                ('hygeine_rating', models.CharField(max_length=1)),
                ('taste_rating', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendor_p1',
        ),
        migrations.AddField(
            model_name='submitters',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_data_collection.Vendor'),
        ),
        migrations.AddField(
            model_name='menu',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_data_collection.Vendor'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_data_collection.Vendor'),
        ),
    ]
