# Generated by Django 2.0.6 on 2018-06-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_data_collection', '0003_auto_20180627_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('vendor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendor_data_collection.Vendor')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
